# IMPORTANT: Generate new secrets before deployment
# Use: echo -n "your-secret" | base64

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: microservices-app
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: bXlzZWNyZXRzdHJpbmc=  # Generate strong password
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: microservices-app
type: Opaque
data:
  access-secret: bXlzZWNyZXRzdHJpbmc=   # Generate 256-bit secret
  refresh-secret: bXlzdXBlcnNlY3JldHN0cmluZw==  # Generate 256-bit secret