apiVersion: v2
name: microservices-app
description: A modern microservices application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservices
  - nodejs
  - react
  - kubernetes