global:
  registry: ghcr.io
  repository: yourorg/microservices-app
  tag: latest
  pullPolicy: IfNotPresent

authService:
  enabled: true
  replicaCount: 3
  image:
    repository: auth-service
  service:
    type: ClusterIP
    port: 80
    targetPort: 3001
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  env:
    NODE_ENV: production
    PORT: "3001"

userService:
  enabled: true
  replicaCount: 3
  image:
    repository: user-service
  service:
    type: ClusterIP
    port: 80
    targetPort: 3002
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: frontend
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api-tls-secret
      hosts:
        - api.yourdomain.com

postgresql:
  enabled: true
  auth:
    postgresPassword: "changeme"
    database: "microservices_db"
  primary:
    persistence:
      enabled: true
      size: 8Gi